Awesome books: with ES6
Abenezer-Tilahun/Awesome-books-with-ES6 pull request #1
Opened 2022-02-21 19:08 UTC by Abenezer-Tilahun

2022-02-21 19:57 UTC, mikethreels requested changes
Hi Abenezer, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-21 19:57 UTC, mikethreels commented on README.md
> +This project is [MIT](./LICENCE) licensed.
- [ ] the link to the license is not working as intended at the moment, have another look at [the template ](https://github.com/microverseinc/readme-template)provided by Microverse for an example on how it is supposed to look like.

2022-02-21 19:57 UTC, mikethreels commented on index.js
> +UpdateDisplay.formBtn.addEventListener('click', UpdateDisplay.addBooks);
- [ ] according to the below requirements you should Install the Luxon Library as a package using your preferred package manager and import it as a module instead of placing the files in your repo.
- [ ] Display the current date below the navigation bar. - For this requirement you should use a library - [Luxon](https://moment.github.io/luxon/#/install)

    - Install it as a npm package: `npm install --save luxon`.
    - Import it as a module.

2022-02-21 20:03 UTC, Abenezer-Tilahun commented on index.js
> +UpdateDisplay.formBtn.addEventListener('click', UpdateDisplay.addBooks);
@ [mikethreels](https://github.com/mikethreels)
i already install npm install --save luxon. and Import it as a module. inside the folder luxon inside the module directory.

2022-02-22 07:42 UTC, merged

2022-04-09 20:16 UTC, Abenezer-Tilahun commented on README.md
> +This project is [MIT](./LICENCE) licensed.
Ok i will correct the link to the license .